export const LANG_META: Record<string, { name: string; flag: string }> = {
  af: { name: 'Afrikaans', flag: '🇿🇦' },
  ar: { name: 'Arabic', flag: '🇸🇦' },
  az: { name: 'Azerbaijani', flag: '🇦🇿' },
  be: { name: 'Belarusian', flag: '🇧🇾' },
  bg: { name: 'Bulgarian', flag: '🇧🇬' },
  bn: { name: 'Bengali', flag: '🇧🇩' },
  ca: { name: 'Catalan', flag: '🏴󠁥󠁳󠁣󠁴󠁿' },
  cs: { name: 'Czech', flag: '🇨🇿' },
  da: { name: 'Danish', flag: '🇩🇰' },
  de: { name: 'German', flag: '🇩🇪' },
  el: { name: 'Greek', flag: '🇬🇷' },
  en: { name: 'English', flag: '🇬🇧' },
  es: { name: 'Spanish', flag: '🇪🇸' },
  'es-la': { name: 'Spanish (Latin America)', flag: '🌎' },
  et: { name: 'Estonian', flag: '🇪🇪' },
  fa: { name: 'Persian', flag: '🇮🇷' },
  fi: { name: 'Finnish', flag: '🇫🇮' },
  fil: { name: 'Filipino', flag: '🇵🇭' },
  fr: { name: 'French', flag: '🇫🇷' },
  he: { name: 'Hebrew', flag: '🇮🇱' },
  hi: { name: 'Hindi', flag: '🇮🇳' },
  hr: { name: 'Croatian', flag: '🇭🇷' },
  hu: { name: 'Hungarian', flag: '🇭🇺' },
  id: { name: 'Indonesian', flag: '🇮🇩' },
  it: { name: 'Italian', flag: '🇮🇹' },
  ja: { name: 'Japanese', flag: '🇯🇵' },
  'ja-ro': { name: 'Japanese (Romanized)', flag: '🇯🇵' },
  ka: { name: 'Georgian', flag: '🇬🇪' },
  kk: { name: 'Kazakh', flag: '🇰🇿' },
  km: { name: 'Khmer', flag: '🇰🇭' },
  ko: { name: 'Korean', flag: '🇰🇷' },
  'ko-ro': { name: 'Korean (Romanized)', flag: '🇰🇷' },
  lt: { name: 'Lithuanian', flag: '🇱🇹' },
  lv: { name: 'Latvian', flag: '🇱🇻' },
  mk: { name: 'Macedonian', flag: '🇲🇰' },
  ml: { name: 'Malayalam', flag: '🇮🇳' },
  mn: { name: 'Mongolian', flag: '🇲🇳' },
  ms: { name: 'Malay', flag: '🇲🇾' },
  my: { name: 'Burmese', flag: '🇲🇲' },
  ne: { name: 'Nepali', flag: '🇳🇵' },
  nl: { name: 'Dutch', flag: '🇳🇱' },
  no: { name: 'Norwegian', flag: '🇳🇴' },
  pl: { name: 'Polish', flag: '🇵🇱' },
  pt: { name: 'Portuguese', flag: '🇵🇹' },
  'pt-br': { name: 'Portuguese (Brazil)', flag: '🇧🇷' },
  ro: { name: 'Romanian', flag: '🇷🇴' },
  ru: { name: 'Russian', flag: '🇷🇺' },
  sk: { name: 'Slovak', flag: '🇸🇰' },
  sl: { name: 'Slovenian', flag: '🇸🇮' },
  sq: { name: 'Albanian', flag: '🇦🇱' },
  sr: { name: 'Serbian', flag: '🇷🇸' },
  sv: { name: 'Swedish', flag: '🇸🇪' },
  ta: { name: 'Tamil', flag: '🇮🇳' },
  te: { name: 'Telugu', flag: '🇮🇳' },
  th: { name: 'Thai', flag: '🇹🇭' },
  tr: { name: 'Turkish', flag: '🇹🇷' },
  uk: { name: 'Ukrainian', flag: '🇺🇦' },
  ur: { name: 'Urdu', flag: '🇵🇰' },
  uz: { name: 'Uzbek', flag: '🇺🇿' },
  vi: { name: 'Vietnamese', flag: '🇻🇳' },
  zh: { name: 'Chinese (Simplified)', flag: '🇨🇳' },
  'zh-hk': { name: 'Chinese (Traditional)', flag: '🇭🇰' },
  'zh-ro': { name: 'Chinese (Romanized)', flag: '🇨🇳' },
}

export function getLangLabel(code: string): string {
  const meta = LANG_META[code]
  if (!meta) return code.toUpperCase()
  return `${meta.flag} ${meta.name}`
}
